encoding_converter: encoding_converter.c
	gcc -Wall -Wextra -Wpedantic -std=c11 encoding_converter.c -o encoding_converter

all: encoding_converter

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions encoding_converter

.PHONY: clean
