telehack_client: telehack_client.c
	gcc -g -Wall -Wextra -Wpedantic -std=c11 telehack_client.c -o telehack_client

all: telehack_client

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions telehack_client

.PHONY: clean
