crc32_calculator: crc32_calculator.c
	gcc -Wall -Wextra -Wpedantic -std=c11 crc32_calculator.c -o crc32_calculator

all: crc32_calculator

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions crc32_calculator

.PHONY: clean
