archive_checker: archive_check.c
	gcc -Wall -Wextra -Wpedantic -std=c11 archive_check.c -o archive_checker

all: archive_checker

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions archive_checker

.PHONY: clean
